### ISSUE TITLE
Permission groups

### ISSUE THREAD

**Issue by LJNIC** [Atherys-Horizons/AtherysTowns#68] opened 2019-09-18 02:19 UTC
As mayor, giving each resident the specific set of permissions you want them to have is slow and annoying. Implementing some basic groups (like Towny has: assistants & co-mayors) would help alleviate some of that. These should be configurable globally.

**Comment by HaedHutner** [comment] 2019-09-27 12:42
A suggestion for how you might implement this. Lets say these "groups" are called "Role(s)", and each one contains a collection of permissions.

From the get-go, you get 2 types of roles. You have TownRole(s) and NationRole(s). This is because there are NationPermission(s) and TownPermission(s), and Residents have permissions on both their town, and the town's nation ( hence the need for NationPermission(s) ).

So, each Role will need to contain a collection of their respective permissions. But not only. A Resident also contains permissions for the world, in the context of a plot or town. These permissions answer questions like "Can player X build within the plot belonging to town Y?" or "Can player X build within plot Z?".

As such, TownRole(s) will also have to contain a collection of WorldPermissions.

Roles could be configured in the following way in the Towns configuration file:

```
roles {
    nation-roles [
        {
            id = "leader"
            name = "Leader"
            nation-permissions [
                "DEPOSIT",
                "WITHDRAW",
                ...
            ]
        },
        {
            ...
        }
    ]
    town-roles [
        {
            id = "mayor"
            name = "Mayor"
            town-permissions [
                "DEPOSIT",
                "WITHDRAW",
                ...
            ],
            world-permissions [
                "BUILD",
                "DESTROY",
                "DAMAGE_ENTITY",
                ...
            ]
        },
        {
            ...
        }
    ]
}
```

**Comment by HaedHutner** [comment] 2020-02-25 15:16
Duplicate of https://github.com/Atherys-Horizons/AtherysTowns/issues/71

**Closed by HaedHutner** 2020-02-25 15:16 UTC
Labels: duplicate
